### PR TITLE
CUDA stream optimisation

### PR DESCRIPTION
**Pull request by envidian**
- Adds argument paired_batch_size for specifying fast 1:1 pairing
- Adds custom handlers for paired_batch_size
- Defines JSON schema for specifying 1:1 combinations and config
- Adds use_fast_math support in cmake build (default enabled)
- Fix memory leaks in Autodock Vina scoring_function reported by Valgrind
- Fix missing CUDA memory initialisation that causes crashes

The original code flow is retained when paired_batch_size is not specified.
Please refer the README for using the paired_batch_size argument.

This commit reverts previous request, and makes the code aligned with original code-flow.

### CODE REVIEW

**Comment by envidian** [comment]
Is there any additional information required for this to be reviewed ? @ysyecust  Thanks.

**Comment by ysyecust** [comment]
@envidian  Thank you very much for your pull request. To further enhance this section, if you could add an example of using 1:1 docking in the example folder, I believe it would make it even more perfect and greatly facilitate other users. We would greatly appreciate your consideration of this suggestion.

**Comment by envidian** [comment]
Thank you. I added https://github.com/dptech-corp/Uni-Dock/commit/5def75620d13b73e371ec7993f903c5bfe65b413 to address the comment. Can you please check ? @ysyecust

**Review by caic99 — APPROVED** [review]
LGTM. @envidian Thank you for your contribution!
@ysyecust plz review

**Pull request merged**
